import { useEffect, useState } from 'react';
import { Building2, Church, FileText, Image, LogOut, Newspaper, Plus, RefreshCw, ShieldCheck, Store } from 'lucide-react';
import { signInAdmin, signOutAdmin, supabase } from '../services/contentRepository';

export function AdminDashboard() {
  const [session, setSession] = useState<any>(null);
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState('');
  useEffect(() => { if (!supabase) return; supabase.auth.getSession().then(({data})=>setSession(data.session)); const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return ()=>data.subscription.unsubscribe(); }, []);
  if (!session) return <div className="admin-login"><div className="admin-login-card"><div className="brand-mark"><ShieldCheck/></div><h2>Panel de administración</h2><p>Luz de Arica</p><input type="email" placeholder="Correo administrador" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Contraseña" value={password} onChange={e=>setPassword(e.target.value)}/>{error&&<div className="error-msg">{error}</div>}<button className="primary" onClick={async()=>{try{setError('');await signInAdmin(email,password)}catch(e:any){setError(e.message)}}}>Ingresar</button></div></div>;
  const run = async (endpoint:string) => { try { const url=(import.meta.env.VITE_API_BASE_URL||'')+endpoint; await fetch(url,{method:'POST'}); alert('Proceso ejecutado correctamente.'); } catch { alert('No se pudo ejecutar el proceso.'); } };
  return <section className="admin-dashboard"><div className="admin-dash-head"><div><span className="eyebrow">CONTROL CENTRAL</span><h2>Panel de Luz de Arica</h2><p>Gestiona el contenido y las automatizaciones.</p></div><button className="secondary" onClick={signOutAdmin}><LogOut size={16}/> Cerrar sesión</button></div><div className="admin-cards"><article><Church/><b>Iglesias</b><span>Agregar, verificar y actualizar iglesias.</span><button><Plus size={15}/> Gestionar</button></article><article><Store/><b>Negocios cristianos</b><span>Administra la huincha de emprendimientos.</span><button><Plus size={15}/> Gestionar</button></article><article><Newspaper/><b>Noticias de Arica</b><span>Publica y actualiza noticias locales.</span><button><Plus size={15}/> Nueva noticia</button></article><article><FileText/><b>Devocional</b><span>Genera el contenido del día con IA.</span><button onClick={()=>run('/api/daily-content')}><RefreshCw size={15}/> Generar</button></article><article><Image/><b>Imagen diaria</b><span>Genera y guarda la imagen del versículo.</span><button onClick={()=>run('/api/generate-image')}><Image size={15}/> Generar imagen</button></article><article><Building2/><b>Estado del sistema</b><span>Supabase, IA y automatizaciones.</span><button className="status"><span className="dot"/> Servicios configurados</button></article></div></section>
}
